### ISSUE TITLE
Call to undefined function caldera_warnings_dismissible_notice()

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/cf-edd-pro#1]
[03-Mar-2017 02:06:40 UTC] PHP Fatal error: Uncaught Error: Call to undefined function caldera_warnings_dismissible_notice() in /home/freeaust/website/wp-content/plugins/cf-edd-pro-1.0.2-R3ZdrD/cf-edd-pro.php:80
Stack trace:
#0 /home/freeaust/website.com/wp-includes/class-wp-hook.php(298): cf_edd_pro_init('')
#1 /home/freeaust/website.com/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /home/freeaust/website.com/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/freeaust/website.com/wp-settings.php(326): do_action('plugins_loaded')
#4 /home/freeaust/website.com/wp-config.php(96): require_once('/home/freeaust/...')
#5 /home/freeaust/website.com/wp-load.php(37): require_once('/home/freeaust/...')
#6 /home/freeaust/website.com/wp-admin/admin.php(31): require_once('/home/freeaust/...')
#7 /home/freeaust/website.com/wp-admin/index.php(10): require_once('/home/freeaust/...')
#8 {main}
thrown in /home/freeaust/website.com/wp-content/plugins/cf-edd-pro-1.0.2-R3ZdrD/cf-edd-pro.php on line 80

**Comment by Shelob9** [comment]
I fixed this in January and didn't update 8df05715d7df59f0fef81d47fcf9217ce9547b2a
